# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contract.v1 import contract_pb2 as contract_dot_v1_dot_contract__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in contract/v1/contract_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RegistryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/contract.v1.RegistryService/RegisterAgent',
                request_serializer=contract_dot_v1_dot_contract__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=contract_dot_v1_dot_contract__pb2.RegisterAgentResponse.FromString,
                _registered_method=True)
        self.UnregisterAgent = channel.unary_unary(
                '/contract.v1.RegistryService/UnregisterAgent',
                request_serializer=contract_dot_v1_dot_contract__pb2.UnregisterAgentRequest.SerializeToString,
                response_deserializer=contract_dot_v1_dot_contract__pb2.UnregisterAgentResponse.FromString,
                _registered_method=True)
        self.GetAgent = channel.unary_unary(
                '/contract.v1.RegistryService/GetAgent',
                request_serializer=contract_dot_v1_dot_contract__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=contract_dot_v1_dot_contract__pb2.GetAgentResponse.FromString,
                _registered_method=True)
        self.DiscoverAgents = channel.unary_unary(
                '/contract.v1.RegistryService/DiscoverAgents',
                request_serializer=contract_dot_v1_dot_contract__pb2.DiscoverAgentsRequest.SerializeToString,
                response_deserializer=contract_dot_v1_dot_contract__pb2.DiscoverAgentsResponse.FromString,
                _registered_method=True)
        self.ReportHealth = channel.unary_unary(
                '/contract.v1.RegistryService/ReportHealth',
                request_serializer=contract_dot_v1_dot_contract__pb2.ReportHealthRequest.SerializeToString,
                response_deserializer=contract_dot_v1_dot_contract__pb2.ReportHealthResponse.FromString,
                _registered_method=True)


class RegistryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=contract_dot_v1_dot_contract__pb2.RegisterAgentRequest.FromString,
                    response_serializer=contract_dot_v1_dot_contract__pb2.RegisterAgentResponse.SerializeToString,
            ),
            'UnregisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterAgent,
                    request_deserializer=contract_dot_v1_dot_contract__pb2.UnregisterAgentRequest.FromString,
                    response_serializer=contract_dot_v1_dot_contract__pb2.UnregisterAgentResponse.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=contract_dot_v1_dot_contract__pb2.GetAgentRequest.FromString,
                    response_serializer=contract_dot_v1_dot_contract__pb2.GetAgentResponse.SerializeToString,
            ),
            'DiscoverAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverAgents,
                    request_deserializer=contract_dot_v1_dot_contract__pb2.DiscoverAgentsRequest.FromString,
                    response_serializer=contract_dot_v1_dot_contract__pb2.DiscoverAgentsResponse.SerializeToString,
            ),
            'ReportHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportHealth,
                    request_deserializer=contract_dot_v1_dot_contract__pb2.ReportHealthRequest.FromString,
                    response_serializer=contract_dot_v1_dot_contract__pb2.ReportHealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contract.v1.RegistryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contract.v1.RegistryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegistryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contract.v1.RegistryService/RegisterAgent',
            contract_dot_v1_dot_contract__pb2.RegisterAgentRequest.SerializeToString,
            contract_dot_v1_dot_contract__pb2.RegisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contract.v1.RegistryService/UnregisterAgent',
            contract_dot_v1_dot_contract__pb2.UnregisterAgentRequest.SerializeToString,
            contract_dot_v1_dot_contract__pb2.UnregisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contract.v1.RegistryService/GetAgent',
            contract_dot_v1_dot_contract__pb2.GetAgentRequest.SerializeToString,
            contract_dot_v1_dot_contract__pb2.GetAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiscoverAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contract.v1.RegistryService/DiscoverAgents',
            contract_dot_v1_dot_contract__pb2.DiscoverAgentsRequest.SerializeToString,
            contract_dot_v1_dot_contract__pb2.DiscoverAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contract.v1.RegistryService/ReportHealth',
            contract_dot_v1_dot_contract__pb2.ReportHealthRequest.SerializeToString,
            contract_dot_v1_dot_contract__pb2.ReportHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OrchestratorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTask = channel.unary_unary(
                '/contract.v1.OrchestratorService/SubmitTask',
                request_serializer=contract_dot_v1_dot_contract__pb2.SubmitTaskRequest.SerializeToString,
                response_deserializer=contract_dot_v1_dot_contract__pb2.SubmitTaskResponse.FromString,
                _registered_method=True)


class OrchestratorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=contract_dot_v1_dot_contract__pb2.SubmitTaskRequest.FromString,
                    response_serializer=contract_dot_v1_dot_contract__pb2.SubmitTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contract.v1.OrchestratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contract.v1.OrchestratorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestratorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contract.v1.OrchestratorService/SubmitTask',
            contract_dot_v1_dot_contract__pb2.SubmitTaskRequest.SerializeToString,
            contract_dot_v1_dot_contract__pb2.SubmitTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTask = channel.unary_unary(
                '/contract.v1.AgentService/ExecuteTask',
                request_serializer=contract_dot_v1_dot_contract__pb2.ExecuteTaskRequest.SerializeToString,
                response_deserializer=contract_dot_v1_dot_contract__pb2.ExecuteTaskResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=contract_dot_v1_dot_contract__pb2.ExecuteTaskRequest.FromString,
                    response_serializer=contract_dot_v1_dot_contract__pb2.ExecuteTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contract.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contract.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contract.v1.AgentService/ExecuteTask',
            contract_dot_v1_dot_contract__pb2.ExecuteTaskRequest.SerializeToString,
            contract_dot_v1_dot_contract__pb2.ExecuteTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
